# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-11 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIS', '0012_auto_20160802_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='selected_subject',
        ),
        migrations.RemoveField(
            model_name='selectedsubject',
            name='student',
        ),
        migrations.RemoveField(
            model_name='selectedsubject',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='faculty',
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
        migrations.DeleteModel(
            name='SelectedSubject',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
