# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-15 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIS', '0013_auto_20190412_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverecord',
            name='vacation_leave',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='type',
            field=models.IntegerField(choices=[(1, 'Sick'), (2, 'Casual'), (3, 'Earned'), (4, 'Vacation')], default=3),
        ),
    ]
