# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-17 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIS', '0014_auto_20190415_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverecord',
            name='casual_leave',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='leaverecord',
            name='earned_leave',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='leaverecord',
            name='sick_leave',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='type',
            field=models.IntegerField(choices=[(1, 'Medical'), (2, 'Casual'), (3, 'Earned'), (4, 'Vacation')], default=3),
        ),
    ]
