# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-24 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SIS', '0016_auto_20190424_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
