# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-24 18:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SIS', '0017_auto_20190425_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='end',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 18, 40, 24, 212155, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='start',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 18, 40, 24, 212155, tzinfo=utc)),
        ),
    ]
